In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"city": ["A", "B", "A", "C", "B"]})

df

  city
0    A
1    B
2    A
3    C
4    B

In [3]:
df_encoded = pd.get_dummies(df, columns=["city"])

df_encoded

   city_A  city_B  city_C
0    True   False   False
1   False    True   False
2    True   False   False
3   False   False    True
4   False    True   False

alternative in sklearn:

In [4]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df[["city"]])

encoded

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [5]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
df[["city_ordinal"]] = encoder.fit_transform(df[["city"]])

df

  city  city_ordinal
0    A           0.0
1    B           1.0
2    A           0.0
3    C           2.0
4    B           1.0

In [6]:
freq = df["city"].value_counts()
df["city_freq"] = df["city"].map(freq)

df

  city  city_ordinal  city_freq
0    A           0.0          2
1    B           1.0          2
2    A           0.0          2
3    C           2.0          1
4    B           1.0          2