In [1]:
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
# sample data
df = pd.DataFrame({
    "age": [25, 30, None, 40],
    "income": [50000, None, 60000, 80000],
    "city": ["A", "B", None, "A"]
})

In [3]:
df["income_missing"] = df["income"].isna().astype(int)

In [4]:
# numerical imputation (mean)
num_imputer = SimpleImputer(strategy="mean")
df[["age", "income"]] = num_imputer.fit_transform(df[["age", "income"]])

In [5]:
# categorical imputation (most frequent)
cat_imputer = SimpleImputer(strategy="most_frequent")
df[["city"]] = cat_imputer.fit_transform(df[["city"]])

In [6]:
df

         age        income city  income_missing
0  25.000000  50000.000000    A               0
1  30.000000  63333.333333    B               1
2  31.666667  60000.000000    A               0
3  40.000000  80000.000000    A               0

In [7]:
# sample data
df = pd.DataFrame({
    "ts": [1, 3, None, 4, 2]
})

In [8]:
df["forward_fill"] = df["ts"].ffill()
df["backward_fill"] = df["ts"].bfill()

In [9]:
df

    ts  forward_fill  backward_fill
0  1.0           1.0            1.0
1  3.0           3.0            3.0
2  NaN           3.0            4.0
3  4.0           4.0            4.0
4  2.0           2.0            2.0